// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OuterMessage.proto

package com.yp.gameframwrok.model.message;

public final class OuterMessage {
  private OuterMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataPackageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:outer.message.DataPackage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 mainType = 1;</code>
     */
    int getMainType();

    /**
     * <code>int32 subType = 2;</code>
     */
    int getSubType();

    /**
     * <code>bytes data = 3;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>int32 errorCode = 4;</code>
     */
    int getErrorCode();
  }
  /**
   * Protobuf type {@code outer.message.DataPackage}
   */
  public  static final class DataPackage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:outer.message.DataPackage)
      DataPackageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataPackage.newBuilder() to construct.
    private DataPackage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataPackage() {
      mainType_ = 0;
      subType_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
      errorCode_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataPackage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              mainType_ = input.readInt32();
              break;
            }
            case 16: {

              subType_ = input.readInt32();
              break;
            }
            case 26: {

              data_ = input.readBytes();
              break;
            }
            case 32: {

              errorCode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OuterMessage.internal_static_outer_message_DataPackage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OuterMessage.internal_static_outer_message_DataPackage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DataPackage.class, Builder.class);
    }

    public static final int MAINTYPE_FIELD_NUMBER = 1;
    private int mainType_;
    /**
     * <code>int32 mainType = 1;</code>
     */
    public int getMainType() {
      return mainType_;
    }

    public static final int SUBTYPE_FIELD_NUMBER = 2;
    private int subType_;
    /**
     * <code>int32 subType = 2;</code>
     */
    public int getSubType() {
      return subType_;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 3;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int ERRORCODE_FIELD_NUMBER = 4;
    private int errorCode_;
    /**
     * <code>int32 errorCode = 4;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mainType_ != 0) {
        output.writeInt32(1, mainType_);
      }
      if (subType_ != 0) {
        output.writeInt32(2, subType_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(3, data_);
      }
      if (errorCode_ != 0) {
        output.writeInt32(4, errorCode_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mainType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, mainType_);
      }
      if (subType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, subType_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, errorCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DataPackage)) {
        return super.equals(obj);
      }
      DataPackage other = (DataPackage) obj;

      boolean result = true;
      result = result && (getMainType()
          == other.getMainType());
      result = result && (getSubType()
          == other.getSubType());
      result = result && getData()
          .equals(other.getData());
      result = result && (getErrorCode()
          == other.getErrorCode());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MAINTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMainType();
      hash = (37 * hash) + SUBTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getSubType();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DataPackage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataPackage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataPackage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataPackage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataPackage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataPackage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataPackage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DataPackage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DataPackage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DataPackage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DataPackage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DataPackage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DataPackage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code outer.message.DataPackage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:outer.message.DataPackage)
        DataPackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OuterMessage.internal_static_outer_message_DataPackage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OuterMessage.internal_static_outer_message_DataPackage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DataPackage.class, Builder.class);
      }

      // Construct using outer.message.OuterMessage.DataPackage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        mainType_ = 0;

        subType_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        errorCode_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OuterMessage.internal_static_outer_message_DataPackage_descriptor;
      }

      public DataPackage getDefaultInstanceForType() {
        return DataPackage.getDefaultInstance();
      }

      public DataPackage build() {
        DataPackage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DataPackage buildPartial() {
        DataPackage result = new DataPackage(this);
        result.mainType_ = mainType_;
        result.subType_ = subType_;
        result.data_ = data_;
        result.errorCode_ = errorCode_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DataPackage) {
          return mergeFrom((DataPackage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DataPackage other) {
        if (other == DataPackage.getDefaultInstance()) return this;
        if (other.getMainType() != 0) {
          setMainType(other.getMainType());
        }
        if (other.getSubType() != 0) {
          setSubType(other.getSubType());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DataPackage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DataPackage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int mainType_ ;
      /**
       * <code>int32 mainType = 1;</code>
       */
      public int getMainType() {
        return mainType_;
      }
      /**
       * <code>int32 mainType = 1;</code>
       */
      public Builder setMainType(int value) {
        
        mainType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 mainType = 1;</code>
       */
      public Builder clearMainType() {
        
        mainType_ = 0;
        onChanged();
        return this;
      }

      private int subType_ ;
      /**
       * <code>int32 subType = 2;</code>
       */
      public int getSubType() {
        return subType_;
      }
      /**
       * <code>int32 subType = 2;</code>
       */
      public Builder setSubType(int value) {
        
        subType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 subType = 2;</code>
       */
      public Builder clearSubType() {
        
        subType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 3;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 3;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 3;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>int32 errorCode = 4;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>int32 errorCode = 4;</code>
       */
      public Builder setErrorCode(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 errorCode = 4;</code>
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:outer.message.DataPackage)
    }

    // @@protoc_insertion_point(class_scope:outer.message.DataPackage)
    private static final DataPackage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DataPackage();
    }

    public static DataPackage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataPackage>
        PARSER = new com.google.protobuf.AbstractParser<DataPackage>() {
      public DataPackage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DataPackage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataPackage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DataPackage> getParserForType() {
      return PARSER;
    }

    public DataPackage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_outer_message_DataPackage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_outer_message_DataPackage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022OuterMessage.proto\022\router.message\"Q\n\013D" +
      "ataPackage\022\020\n\010mainType\030\001 \001(\005\022\017\n\007subType\030" +
      "\002 \001(\005\022\014\n\004data\030\003 \001(\014\022\021\n\terrorCode\030\004 \001(\005b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_outer_message_DataPackage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_outer_message_DataPackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_outer_message_DataPackage_descriptor,
        new String[] { "MainType", "SubType", "Data", "ErrorCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
